### ISSUE TITLE
Better autogenerated Docs input parameters handling

### ISSUE THREAD

**Issue by tynods** [OxygenFramework/Oxygen.jl#155]
Hi,

Having the autogenerated Swagger docs is great.
But it could be better with a better handling of input parameters.
I tried the autogenerated docs for various of the example code of the documentation.
For instance, the code provided in the Manual, section Path Parameters / Additional Parameter Type Support, provides an autogenerated docs that is almost not trialable. Most of the API entries are not correctly encoded, leading to servers errors.

Regarding POST requests (for example: Manual / Request Body), the autogenerated doc doesn't provide an input field for the request body, so we can't try the endpoint.

It would be great to have an autogenerated documentation that would allow to test all, if not most, of the defined APIs :-)

Thanks!

**Comment by ndortega** [comment]
Hi @tynods, 

The reason you see the errors from the swagger docs is based on how it's formatting the inputs to send to the backend. 
There's this one excerpt from the docs which explains this portion:

> In most cases, Oxygen uses the built-in parse() function to parse incoming parameters. But when the parameter types start getting more complex (eg. Vector{Int64} or a custom struct), then Oxygen assumes the parameter is a JSON string and uses the JSON3 library to serialize the parameter into the corresponding type

Basically swagger is passing elements like "1,2,3" and expecting oxygen to parse this correclty as a list of integers, while the server was expecting a valid json string like "[1,2,3]". To fix this we could look for datastructures and try to "fix" them before going parsing and typecasting them.

This was always just a "neat" feature that was included which didn't require much code to get working, but as you can see it's definitley not bulletproof - especially when integrating with the internal docs.

**Comment by tynods** [comment]
The autogenerated docs was a significant factor in my starting to use Oxygen :-)
I understand that for GET requests, not all parameter types are suitable.
However, the most important immediate point seems to me to be the ability to enter the body of POST/PUT requests.

**Comment by ndortega** [comment]
@tynods 
This change just went live in v1.4.9, now all post, put, and patch requests have an optional request body you can customize through the autogenerated docs
