### ISSUE TITLE
 Performance issue calling another API? 

### ISSUE THREAD

**Issue by AbrJA** [OxygenFramework/Oxygen.jl#169]
Hi @ndortega,

Congratulations for this great package, I'm using it a lot even into a prod environments

Recently I'm using it with AWS.jl to reach a SageMaker endpoint but I notice a performance issue (maybe due to my ignorance). I use [invoke_endpoint](https://github.com/JuliaCloud/AWS.jl/blob/master/src/services/sagemaker_runtime.jl#L66) that it is just a POST request. 

I tried to recreate a minimal example:

1) When I run this API (with a 150 ms sleep to simulate the time taken by the SageMaker endpoint):

``` 
using Oxygen

@get "/model" function()
    sleep(0.15)
    return """{ok}"""
end

serve(port = 8001)
```

I reach about 560 RPS (with concurrency = 100)

ab -n1000 -c100 'http://localhost:8001/model'

``` 
Server Software:        
Server Hostname:        localhost
Server Port:            8001

Document Path:          /model
Document Length:        4 bytes

Concurrency Level:      100
Time taken for tests:   1.756 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      83000 bytes
HTML transferred:       4000 bytes
Requests per second:    569.62 [#/sec] (mean)
Time per request:       175.556 [ms] (mean)
Time per request:       1.756 [ms] (mean, across all concurrent requests)
Transfer rate:          46.17 [Kbytes/sec] received
```

2) When I simulate an Oxygen API consuming the SageMaker endpoint

```
using Oxygen
using HTTP

@get "/test" function()
    response = HTTP.get("http://localhost:8001/model")
    return String(response.body)
end

serve(port = 8002)
```

I reach only around 100 RPS (ab -n1000 -c100 'http://localhost:8002/test') even using 4 threads with serveparallel. I would expect to see a number of RPS closer to 560 

```
Server Software:        
Server Hostname:        localhost
Server Port:            8002

Document Path:          /test
Document Length:        4 bytes

Concurrency Level:      100
Time taken for tests:   9.815 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      83000 bytes
HTML transferred:       4000 bytes
Requests per second:    101.89 [#/sec] (mean)
Time per request:       981.455 [ms] (mean)
Time per request:       9.815 [ms] (mean, across all concurrent requests)
Transfer rate:          8.26 [Kbytes/sec] received
```

If I do the same with FastAPI

```
import requests
from fastapi import FastAPI

app = FastAPI()

@app.get("/test")
def test():
    response = requests.get("http://localhost:8001/model")
    return response.text
``` 

With one worker (uvicorn api_test_nested:app --host 0.0.0.0 --port 8003 --workers 1) I get (ab -n1000 -c100 'http://localhost:8003/test') around 220 RPS

```
Server Software:        uvicorn
Server Hostname:        localhost
Server Port:            8003

Document Path:          /test
Document Length:        6 bytes

Concurrency Level:      100
Time taken for tests:   4.436 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      149000 bytes
HTML transferred:       6000 bytes
Requests per second:    225.42 [#/sec] (mean)
Time per request:       443.618 [ms] (mean)
Time per request:       4.436 [ms] (mean, across all concurrent requests)
Transfer rate:          32.80 [Kbytes/sec] received
```
But using 4 workers I get almost the same RPS from the endpoint simulating SageMaker (500 vs 560)

```
Server Software:        uvicorn
Server Hostname:        localhost
Server Port:            8003

Document Path:          /test
Document Length:        6 bytes

Concurrency Level:      100
Time taken for tests:   2.013 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      149000 bytes
HTML transferred:       6000 bytes
Requests per second:    496.78 [#/sec] (mean)
Time per request:       201.296 [ms] (mean)
Time per request:       2.013 [ms] (mean, across all concurrent requests)
Transfer rate:          72.29 [Kbytes/sec] received
```

I think it could be a HTTP.jl issue of maybe there is a better way to make the requests but I'm new using Julia so if you have a hint, please let me know!

Thanks in advance, and again thanks for your work in this package

Abraham

**Comment by ndortega** [comment]
Hi @AbrJA,

It might come down to the json serialization of the response from AWS.  In your example you're returning the json body as a string from the request handler. When a string is returned from a request handler in Oxygen it will automatically try to detect the content type, but this does come with a decent cost in performance. If you know the content type of a request handler, I'd heavily recommend using one of the render functions to bypass this process.

In the first example below, it can be a little confusing since we have a `json` function doing two different things. The first call loads the json from a Response into a dictionary and the second call converts this data into a properly formatted Response

```julia
# Use the json() helper functions
@get "/test" function()
    response = HTTP.get("http://localhost:8001/model")
    # convert the body of the response to a dictionary
    data = json(response)
    # convert object to HTTP.Response object with a json payload 
    json(data)
end

# Or you could just directly pass the response data through (with appropriate headers set) This is what those helper functions do under the hood
@get "/test2" function()
    response = HTTP.get("http://localhost:8001/model")
    
    headers = [
        "Content-Type" => "application/json; charset=utf-8",
        "Content-Length" => string(sizeof(response.body)),
    ]

    HTTP.Response(response.status, headers, response.body)
end
```

Let me know if you see any improvements or have any other questions

**Comment by AbrJA** [comment]
Hi @ndortega,

Thank you for your quick answer and your suggestions, I tested them but unfortunately I got the same RPS.

I think the issue is not in the serialization part but in the HTTP request (I don't fully understand why). To prove that, I changed the API response to be equal to the `/model` API, the unique difference between both APIs is the HTTP.request instead of sleep(0.15).

```
using Oxygen
using HTTP

@get "/test" function()
    response = HTTP.request("GET", "http://localhost:8001/model") # Similar to sleep(0.15) - Just this line is different
    return """{ok}"""
end

serve(port = 8002)
``` 

Doing the benchmark, again I got just 100 RPS (even with serveparallel) a low number compared to the 560 in `/model` 

```
Server Software:        
Server Hostname:        localhost
Server Port:            8002

Document Path:          /test
Document Length:        4 bytes

Concurrency Level:      100
Time taken for tests:   9.827 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      83000 bytes
HTML transferred:       4000 bytes
Requests per second:    101.76 [#/sec] (mean)
Time per request:       982.679 [ms] (mean)
Time per request:       9.827 [ms] (mean, across all concurrent requests)
Transfer rate:          8.25 [Kbytes/sec] received
```

I have been trying some ideas but I have not been able to solve it. If you have other clues, please let me know!

Again, thank you for your help :)

**Comment by ndortega** [comment]
@AbrJA 

Hmmm, sorry that didn't help. 

- Could you be getting rate-limited by AWS?  I know you can set rate limits on AWS personalize to keep your costs in check
- Have you tried making the [HTTP request asynchronously](https://stackoverflow.com/a/70919004/8364675)?

**Comment by AbrJA** [comment]
Hi @ndortega, I hope you are doing great!

I think I didn't explain myself correctly, I found this issue while using AWS with invoke_endpoint but in my example I don't use it anymore. This issue is not only with AWS but with any HTTP request within an API.

The example I am sharing with you runs locally. I start an API (`/model` - port 8001) and then I build another API (`/test` - port 8002) that makes a request to `/model`.

I tried with asynchronous requests but I didn't get an improvement. However, I changed the `/test` API to **use curl instead of HTTP.jl** and I got a huge improvement so I'm almost sure there is something strange with HTTP.jl
 
```
using Oxygen

@get "/test" function()
    response = run(`curl http://localhost:8001/model`) # instead of HTTP.request("GET", "http://localhost:8001/model")
    return json("ok")
end

serve(port = 8002)
```

**With this small change I go from 100 RPS to about 440 RPS**, much closer to 560 RPS I get from `/model` and twice the RPS from FastAPI with one worker.

I'm going to put my case in the HTTP.jl repository, maybe there someone has an idea why this is happening.  

Thank you very much for your help

**Comment by ndortega** [comment]
Hi @AbrJA , 

That makes sense, it may not be a Oxygen issue at all. But just to clarify - are you using the new `@oxidise` macro to create multiple instances within a single julia program? If so, you can try using the `internalrequest()` function which directly passes a http request to one of your request handlers. 
```julia
module A
    using Oxygen; @oxidise

    @get "/" function()
        text("server A")
    end
end

module B
    using HTTP
    using Oxygen; @oxidise
    using ..A

    @get "/" function()
        text("server B")
    end

    # directly call Sever A from Server B
    @get "/a" function()
        A.internalrequest(HTTP.Request("GET", "/"))
    end
end

try 
    A.serve(port=8001, async=true)
    B.serve(port=8002, async=false)
finally
    A.terminate()
    B.terminate()
end
```

**Comment by AbrJA** [comment]
Hi @ndortega,

Nope, I'm running the APIs independently (one API by script) to better simulate the request to an external endpoint. But it's good to know that new functionality, thanks!

I found this recent issue in the HTTP.jl repository JuliaWeb/HTTP.jl/1153. I have a feeling it's related to this but I'm not sure.

Greetings!

**Comment by ndortega** [comment]
Hi @AbrJA, 

It seems like you were able to resolve this issue on your own, so I'm going to close it for now. If this issue persists or comes back, feel free to open up another issue
