### ISSUE TITLE
Interpolating variables into endpoints with query parameters

### ISSUE THREAD

**Issue by kawild** [OxygenFramework/Oxygen.jl#195]
If I add query parameters to the function definition of the example from [Interpolating variables into endpoints](https://oxygenframework.github.io/Oxygen.jl/stable/#Interpolating-variables-into-endpoints) like:

```
using Oxygen

operations = Dict("add" => +, "multiply" => *)
for (pathname, operator) in operations
    @get "/$pathname/{a}/{b}" function (req, a::Float64, b::Float64, query)
        return operator(a, b)
    end
end

# start the web server
serve()
```

it seems that the value of "query" must be a valid JSON. If not:

┌ Error: ERROR: 
│   exception =
│    ArgumentError: invalid JSON at byte position 1 while parsing type QuoteNode: ExpectedOpeningObjectChar
│    7

Maybe this is intended behavior.

**Comment by ndortega** [comment]
Hi @kawild, 

I've ran this exact snippet on my local in a fresh package with v1.10.3 and this appears to be functioning as expected. In this scenario `query` is a required query param of type Any, which means the query param will be passed directly as a string from the url.

Some follow-up question:

- How are you calling this endpoint? 
- What is your project setup like?

I've tried several variations like the ones listed below and they all appear to be working: 

- http://127.0.0.1:8080/multiply/5/7?query=hello%20world
- http://127.0.0.1:8080/multiply/5/7?query=2
- http://127.0.0.1:8080/multiply/5/7?query=34.4353
- http://127.0.0.1:8080/add/5/7?query=hello%20world
- http://127.0.0.1:8080/add/5/7?query=2
- http://127.0.0.1:8080/add/5/7?query=34.4353

**Comment by kawild** [comment]
After upgrading Julia from 1.10.2 to 1.10.3 and Oxygen from 1.5.7 to 1.5.8 it now works for me as expected too!
Also the more complex application which introduced me this issue and fom which I stripped down this minimal example.
Didn´t change anything else.

Thank you very much!

**Comment by ndortega** [comment]
I'm glad to hear it! 

Now that you mentioned that I think I know what could be causing this issue. When parsing path and query parameters I have a fallback thats used on complex types and assumes  it's a json string and try to parse it.

While this makes things super flexible it does enable people to pass more complex things through  query and path parameters when they most likely shouldn't. In most cases you're much better off passing these values through the body of a request
