### ISSUE TITLE
Every request errors after some time

### ISSUE THREAD

**Issue by kawild** [OxygenFramework/Oxygen.jl#203]
Hi,

a continuous running application with some requests per second becomes unavailable after a few days of running without any problems.
Every request to every path fails because of an internal error, maybe related to some deque from metrics.

The following stacktrace ist inverted by journalctl and some long lines are cut. But I guess for a first view it should be enough.
I will test the application with disabled metrics.

Thanks for this great package!

Jun 06 09:32:59  julia[3904]: └ @ Oxygen.Core.Util ~/.julia/packages/Oxygen/LWjgB/src/utilities/misc.jl:40
Jun 06 09:32:59  julia[3904]: │        @ HTTP.Servers ~/.julia/packages/HTTP/sJD5V/src/Servers.jl:401
Jun 06 09:32:59  julia[3904]: │     [16] (::HTTP.Servers.var"#16#17"{Oxygen.Core.var"#15#16"{Oxygen.Core.var"#29#31"{Oxygen.Core.var"#40#44"{var"#39#40"{Oxygen.Core.var"#34#37"{HTTP.Handlers.Router{typeof(HTTP.Handlers.de>
Jun 06 09:32:59  julia[3904]: │        @ HTTP.Servers ~/.julia/packages/HTTP/sJD5V/src/Servers.jl:469
Jun 06 09:32:59  julia[3904]: │     [15] handle_connection(f::Function, c::HTTP.Connections.Connection{Sockets.TCPSocket}, listener::HTTP.Servers.Listener{Nothing, Sockets.TCPServer}, readtimeout::Int64, access_log::Funct>
Jun 06 09:32:59  julia[3904]: │        @ ./essentials.jl:889 [inlined]
Jun 06 09:32:59  julia[3904]: │     [14] invokelatest
Jun 06 09:32:59  julia[3904]: │        @ ./essentials.jl:892 [inlined]
Jun 06 09:32:59  julia[3904]: │     [13] #invokelatest#2
Jun 06 09:32:59  julia[3904]: │        @ Oxygen.Core ~/.julia/packages/Oxygen/LWjgB/src/core.jl:208
Jun 06 09:32:59  julia[3904]: │     [12] (::Oxygen.Core.var"#15#16"{Oxygen.Core.var"#29#31"{Oxygen.Core.var"#40#44"{var"#39#40"{Oxygen.Core.var"#34#37"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Ha>
Jun 06 09:32:59  julia[3904]: │        @ HTTP.Handlers ~/.julia/packages/HTTP/sJD5V/src/Handlers.jl:58
Jun 06 09:32:59  julia[3904]: │     [11] (::HTTP.Handlers.var"#1#2"{Oxygen.Core.var"#12#14"{Oxygen.Core.var"#29#31"{Oxygen.Core.var"#40#44"{var"#39#40"{Oxygen.Core.var"#34#37"{HTTP.Handlers.Router{typeof(HTTP.Handlers.def>
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/Oxygen/LWjgB/src/core.jl:191 [inlined]
Jun 06 09:32:59  julia[3904]: │     [10] #12
Jun 06 09:32:59  julia[3904]: │        @ Oxygen.Core ~/.julia/packages/Oxygen/LWjgB/src/core.jl:331
Jun 06 09:32:59  julia[3904]: │      [9] (::Oxygen.Core.var"#29#31"{Oxygen.Core.var"#40#44"{var"#39#40"{Oxygen.Core.var"#34#37"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Noth>
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/Oxygen/LWjgB/src/core.jl:358 [inlined]
Jun 06 09:32:59  julia[3904]: │      [8] #40
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/Oxygen/LWjgB/src/utilities/misc.jl:32 [inlined]
Jun 06 09:32:59  julia[3904]: │      [7] handlerequest
Jun 06 09:32:59  julia[3904]: │        @ Oxygen.Core.Util ~/.julia/packages/Oxygen/LWjgB/src/utilities/misc.jl:37
Jun 06 09:32:59  julia[3904]: │      [6] handlerequest(getresponse::Oxygen.Core.var"#41#45"{Request, var"#39#40"{Oxygen.Core.var"#34#37"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default4>
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/Oxygen/LWjgB/src/core.jl:365 [inlined]
Jun 06 09:32:59  julia[3904]: │      [5] #41
Jun 06 09:32:59  julia[3904]: │        @ Base ./lock.jl:229
Jun 06 09:32:59  julia[3904]: │      [4] lock(f::Oxygen.Core.var"#42#46"{Float64, Response, Request, Oxygen.Core.AppContext.Service}, l::ReentrantLock)
Jun 06 09:32:59  julia[3904]: │        @ Oxygen.Core ~/.julia/packages/Oxygen/LWjgB/src/core.jl:367
Jun 06 09:32:59  julia[3904]: │      [3] (::Oxygen.Core.var"#42#46"{Float64, Response, Request, Oxygen.Core.AppContext.Service})()
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/Oxygen/LWjgB/src/metrics.jl:26 [inlined]
Jun 06 09:32:59  julia[3904]: │      [2] push_history
Jun 06 09:32:59  julia[3904]: │        @ ~/.julia/packages/DataStructures/95DJa/src/circ_deque.jl:79 [inlined]
Jun 06 09:32:59  julia[3904]: │      [1] pushfirst!
Jun 06 09:32:59  julia[3904]: │    Stacktrace:
Jun 06 09:32:59  julia[3904]: │    BoundsError
Jun 06 09:32:59  julia[3904]: │   exception =

**Comment by ndortega** [comment]
Hi @kawild, 

Thanks for the logs, I'm sorry you're running into this issue with metrics. You're right on the money, this issue appears to be coming from the metrics collection middleware function.

I will admit this is super weird, I chose a CircularDeque data structure specifically to avoid using too much memory and avoid index out of bounds issues. Is there any more information? You cut off the logs right at the exception which will have the info I need to debug this better. Depending on that log output, we may have to raise this issue with the DataStrutures.jl package if it's something I can't fix within Oxygen.

**Comment by kawild** [comment]
Thanks for your response, but I´m sorry, it seems I don´t have the complete logs anymore.
Also this error is hard to reproduce, because it occured after nearly 2 weeks of runtime and only within an productive environment.

Please let me know, If I can help any further!

**Comment by ndortega** [comment]
No worries, do you have a rough number of requests that were sent? Are the request bodies large? I can setup a server and mock a bunch of requests to see how well it holds up under high load.

If you're not sure how much load your app is getting, I'll try to mock a couple million requests to see how the server holds up over time with metrics enabled.

**Comment by kawild** [comment]
The app has a request rate of about 10/sec. 
The request bodies are empty, because it is also called from Grafana, and there I can not interpolate something into the body, so everything is handled via request parameters.
So the url can be quite long - about 2000 signs and even longer.

**Comment by ndortega** [comment]
I'm going to close this issue for now, feel free to reopen this issue if you run into it again.

**Comment by Fro116** [comment]
Apologies for commenting on a closed issue, but I've ran into this problem as well. I'm running Oxygen v1.5.15 on a webserver with an average request rate of 20/s. This showed up after 5 hours.

┌ Error: ERROR: 
│   exception =
│    BoundsError
│    Stacktrace:
│      [1] pushfirst!
│        @ ~/.julia/packages/DataStructures/95DJa/src/circ_deque.jl:79 [inlined]
│      [2] push_history
│        @ ~/.julia/packages/Oxygen/r5aSn/src/metrics.jl:26 [inlined]
│      [3] (::Oxygen.Core.var"#43#47"{Float64, HTTP.Messages.Response, HTTP.Messages.Request, Oxygen.Core.AppContext.Service})()
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:427
│      [4] lock(f::Oxygen.Core.var"#43#47"{Float64, HTTP.Messages.Response, HTTP.Messages.Request, Oxygen.Core.AppContext.Service}, l::ReentrantLock)
│        @ Base ./lock.jl:232
│      [5] #42
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:425 [inlined]
│      [6] handlerequest(getresponse::Oxygen.Core.var"#42#46"{HTTP.Messages.Request, Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service}, catch_errors::Bool; show_errors::Bool)
│        @ Oxygen.Core.Util ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:35
│      [7] handlerequest
│        @ ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:30 [inlined]
│      [8] #41
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:418 [inlined]
│      [9] (::Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String})(req::HTTP.Messages.Request)
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:391
│     [10] #13
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:247 [inlined]
│     [11] (::HTTP.Handlers.var"#1#2"{Oxygen.Core.var"#13#15"{Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String}, Sockets.IPv4, HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}}})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│        @ HTTP.Handlers ~/.julia/packages/HTTP/WctPa/src/Handlers.jl:58
│     [12] #16
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:264 [inlined]
│     [13] (::Oxygen.Core.var"#20#23"{HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, Oxygen.Core.var"#16#17"{Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String}}})()
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:278
└ @ Oxygen.Core.Util ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:38
┌ Error: ERROR: 
│   exception =
│    BoundsError
│    Stacktrace:
│      [1] pushfirst!
│        @ ~/.julia/packages/DataStructures/95DJa/src/circ_deque.jl:79 [inlined]
│      [2] push_history
│        @ ~/.julia/packages/Oxygen/r5aSn/src/metrics.jl:26 [inlined]
│      [3] (::Oxygen.Core.var"#43#47"{Float64, HTTP.Messages.Response, HTTP.Messages.Request, Oxygen.Core.AppContext.Service})()
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:427
│      [4] lock(f::Oxygen.Core.var"#43#47"{Float64, HTTP.Messages.Response, HTTP.Messages.Request, Oxygen.Core.AppContext.Service}, l::ReentrantLock)
│        @ Base ./lock.jl:232
│      [5] #42
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:425 [inlined]
│      [6] handlerequest(getresponse::Oxygen.Core.var"#42#46"{HTTP.Messages.Request, Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service}, catch_errors::Bool; show_errors::Bool)
│        @ Oxygen.Core.Util ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:35
│      [7] handlerequest
│        @ ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:30 [inlined]
│      [8] #41
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:418 [inlined]
│      [9] (::Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String})(req::HTTP.Messages.Request)
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:391
│     [10] #13
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:247 [inlined]
│     [11] (::HTTP.Handlers.var"#1#2"{Oxygen.Core.var"#13#15"{Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String}, Sockets.IPv4, HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}}})(stream::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}})
│        @ HTTP.Handlers ~/.julia/packages/HTTP/WctPa/src/Handlers.jl:58
│     [12] #16
│        @ ~/.julia/packages/Oxygen/r5aSn/src/core.jl:264 [inlined]
│     [13] (::Oxygen.Core.var"#20#23"{HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.Connections.Connection{Sockets.TCPSocket}}, Oxygen.Core.var"#16#17"{Oxygen.Core.var"#30#32"{Oxygen.Core.var"#41#45"{Oxygen.Core.var"#35#38"{HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, Bool, Bool}, Oxygen.Core.AppContext.Service, Bool}, HTTP.Handlers.Router{typeof(HTTP.Handlers.default404), typeof(HTTP.Handlers.default405), Nothing}, String}}})()
│        @ Oxygen.Core ~/.julia/packages/Oxygen/r5aSn/src/core.jl:278
└ @ Oxygen.Core.Util ~/.julia/packages/Oxygen/r5aSn/src/utilities/misc.jl:38

**Comment by ndortega** [comment]
@Fro116, 

Strange it looks like the circular dequeue data structure I'm using to as part of the server metrics is throwing an internal error. As a quick band-aide patch, I'd recommend turning off server metrics off to bypass this part of the code for your application. set `metrics=false` as part of your `serve()` or `serveparallel()` call

I'll need to release a patch to handle cases where this can fail and also raise an issue with the datastructures package.

**Comment by rori4** [comment]
has this been fixed on newer version @ndortega ? I am running in the same issue on `version = "1.5.5"`

**Comment by ndortega** [comment]
> has this been fixed on newer version [@ndortega](https://github.com/ndortega) ? I am running in the same issue on `version = "1.5.5"`

Not from my end - this patch fell through the cracks. Thanks for  highlighting this, I'll add some error handling to log when records are getting dropped
