### ISSUE TITLE
Request Extractors: Status code on failure

### ISSUE THREAD

**Issue by AbrJA** [OxygenFramework/Oxygen.jl#209]
Hi @ndortega, I hope you are doing well,

The last features you added are really nice, good job man. 

I have just a small question, if the extractor or the validator fails currently it returns a 500 status code (Internal Server Error), wouldn't it be better to return a 400 status code (Bad request)? 

Let me know your thoughts,

Abraham JA

**Comment by ndortega** [comment]
Hi @AbrJA, 

Absolutely, that makes a lot more sense to throw a 400 in that case.
