### ISSUE TITLE
Documentation: Using router with function syntax

### ISSUE THREAD

**Issue by sschmidhuber** [OxygenFramework/Oxygen.jl#222]
Hello,

Could someone give an example how to use the function syntax in combination with a router? Maybe that could be added to https://oxygenframework.github.io/Oxygen.jl/stable/#Routing-Macro-and-Function-Syntax 

This is very easy following the documentation on the macro syntax, but how to do it with function style?

BG Stefan

**Comment by ndortega** [comment]
Thankfully the usage is exactly the same. Here's an example from the tests:

https://github.com/OxygenFramework/Oxygen.jl/blob/v1.5.13/test/routingfunctionstests.jl#L15

**Comment by sschmidhuber** [comment]
Thank you for the hint!

BG Stefan
