### ISSUE TITLE
Hosting swagger /docs/ under reverse proxy URL prefix results in schema not found

### ISSUE THREAD

**Issue by bduncanj** [OxygenFramework/Oxygen.jl#234]
As the title suggests, hosting the Oxygen generated endpoint under a reverse proxy (say, under the URL prefix of `/api/`) results in an error (schema not found) when accessing the Swagger API`/api/docs` on the server.

The path `/api/schema/` is valid but the issue is that the `/docs` page injects the schema using `location.origin`.

Setting the `external_url` argument of `serve()` doesn't help - this is not passed into the function (`swaggerhtml` in `autodoc.jl`).

Is there an existing method to support hosting the Oxygen endpoint under a reverse proxy with a URI prefix?  If not, it seems we could use the `external_url` in `swaggerhtml()` when building the path to include the schema.

**Comment by ndortega** [comment]
Hi @bduncanj, 

Thanks for opening this issue - I don't see why we shouldn't be able to set the host prefix to the `external_url` (if set)

**Comment by ndortega** [comment]
@bduncanj 

Does the `/docs/redoc` endpoint work behind the reverse proxy? The redoc docs uses a relative url to point to the schema - if this works then we can take a similar approach to the default swagger docs

**Comment by bduncanj** [comment]
@ndortega sorry for the delay in getting back to you on this one, but thank you for the quick response!  It sounds like you've found the cause and fixed this.  From my memory the same happened on the `/docs/redoc` URL also for the same reason.

**Comment by ndortega** [comment]
@bduncanj, 
No worries, this time of the year is super busy for everyone. After I didn't hear a response, I just assumed the relative path for the docs were working.

As part of a recent patch I only removed the window.origin part - so it very well could still be failing. If the latest version still isn't working, let me know and I'll reopen this issue and find a way to insert the external_url
